# Generated by Django 4.2.3 on 2023-11-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_user_date_joined_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
