# Generated by Django 4.2.3 on 2023-10-17 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_cart_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0.0)),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('ordered_date', models.DateTimeField()),
                ('payment_type', models.CharField(choices=[('e_banking', 'e_banking'), ('card', 'card'), ('upi', 'upi'), ('cash_on_delivary', 'delivary')], max_length=100)),
                ('payment_status', models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('in_progres', 'in_progres'), ('error', 'error')], max_length=100)),
                ('order_status', models.CharField(choices=[('shipped', 'shipped'), ('delivered', 'delivered'), ('in_progres', 'in_progres'), ('cancelled', 'cancelled')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
