# Generated by Django 4.2.3 on 2023-10-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('online_payment', 'online_payment'), ('cash_on_delivary', 'delivary')], max_length=100),
        ),
    ]
