# Generated by Django 4.2.3 on 2023-10-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_order_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='order_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('online_payment', 'online payment'), ('cash_on_delivary', 'delivary')], max_length=100),
        ),
    ]
