# Generated by Django 4.2.3 on 2023-10-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_order_payment_id_alter_order_provider_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_exclusive',
            field=models.BooleanField(default=False, help_text='0-default, 1-exclusive'),
        ),
    ]
