# Generated by Django 4.2.3 on 2023-10-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_subcategory_remove_category_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subcategores',
            field=models.ManyToManyField(related_name='subcategories', to='shop.subcategory'),
        ),
    ]
