# Generated by Django 4.2.3 on 2023-10-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_category_subcategores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subcategores',
            new_name='subcategories',
        ),
    ]
