# Generated by Django 4.2.3 on 2023-10-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_category_status_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('online_payment', 'online_payment'), ('cash_on_delivery', 'cash_on_delivery')], max_length=100),
        ),
    ]
