# Generated by Django 4.2.3 on 2023-10-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('online_payment', 'online payment'), ('cash_on_delivery', 'cash on delivery')], max_length=100),
        ),
    ]
